#!/bin/bash -e

eth0_mac_addr=$(ip link show eth0 | grep 'link/ether' | awk '{ print $2 }')

cat <<EOF >/etc/network/interfaces
# interfaces(5) file used by ifup(8) and ifdown(8)

# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'

# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

auto lo
        iface lo inet loopback

auto eth0
        iface eth0 inet manual

auth eth1
        iface eth1 inet manual

auto br0
        iface br0 inet dhcp
        bridge_ports eth0 eth1
        bridge_stp off
        post-up /bin/echo -n 1 > /sys/devices/virtual/net/br0/bridge/multicast_querier
        bridge_hw $eth0_mac_addr
EOF
