
$(ROOT_PACKAGE)/version.py: Makefile
	@echo "# This file is automatically generated by Makefile" > $(ROOT_PACKAGE)/version.py
	@echo "__version__ = '${VERSION_STRING}$(UPGRADE_VERSION)'" >> $(ROOT_PACKAGE)/version.py
